tigger status progress

diff --git a/tigger-rm b/tigger-rm
--- a/tigger-rm
+++ b/tigger-rm
@@ -13,29 +13,28 @@ check_file_in_index () {
     fi
 }
 
-# # Get last commit
-# check_unstaged () {
-#     count=0
-#     while true
-#     do 
-#         if [ ! -d ".tigger/$count" ] 
-#         then
-#             echo $count
-#             break
-#         fi
-#         count=$((count + 1))
-#     done
-#     count=$((count - 1))
-#     if [ $count -ge 0 ]
-#     then 
-#         diff=$(diff -r .tigger/"$1" .tigger/index)
-#         if [ ! -z "$diff" ] 
-#         then 
-#             echo "tigger-rm: error: 'c' has staged changes in the index"
-#             exit 1
-#         fi
-#     fi
-# }
+# Throw error if there is any staging differences
+# Usage: check_if_staged <filename>
+check_if_staged () {
+    if [ -f .tigger/last_commit ]
+    then
+        last_commit=$(cat .tigger/last_commit)
+        if [ ! -f .tigger/"$last_commit"/"$1" ] 
+        then 
+            echo "tigger-rm: error: '$1' has staged changes in the index"
+            exit 1
+        fi
+        diff=$(diff -r .tigger/"$last_commit/$1" "$1")
+        if [ ! -z "$diff" ] 
+        then 
+            echo "tigger-rm: error: '$1' has staged changes in the index"
+            exit 1
+        fi
+    else 
+        echo "tigger-rm: error: '$1' has staged changes in the index"
+        exit 1
+    fi
+}
 
 # Delete file from index and current repository
 # Usage: full_delete <filenames...>    
@@ -67,6 +66,7 @@ safe_delete () {
     for file
     do 
         check_file_in_index "$file" 
+        check_if_staged "$file"
         rm .tigger/index/"$file"
         if [ -f "$file" ]
         then
@@ -108,5 +108,5 @@ then
     cache_delete "$@"
 # Case 4: tigger-rm filenames...
 else 
-    echo "NOT DONE"
+    safe_delete "$@"
 fi
diff --git a/tigger-status b/tigger-status
--- a/tigger-status
+++ b/tigger-status
@@ -1,2 +1,76 @@
 #!/bin/dash
 
+######################################################################
+# Helper Functions
+######################################################################
+
+# Error check: .tigger exists 
+check_tigger () {
+    if [ ! -d ".tigger" ]
+    then
+        echo "tigger-commit: error: tigger repository directory .tigger not found"
+        exit 1
+    fi
+}
+
+# Return sorted comma separated list of unique files in index, repository 
+# and current directory (simulate hash table using regex check)
+# Usage: get_new_commit 
+get_unique_files () {
+    str=""
+    # Repository
+    if [ -f .tigger/last_commit ] 
+    then
+        for file in .tigger/"$(cat .tigger/last_commit)"/*
+        do 
+            if [ -f "$file" ]
+            then
+                file=$(echo "$file" | sed -E 's/.tigger\/.*\/(.*)/\1/')
+                str="$str-#$file#-"
+            fi
+        done
+    fi
+    # Index
+    for file in .tigger/index/*
+    do 
+        if [ -f "$file" ]
+        then
+            file=$(echo "$file" | sed -E 's/.tigger\/.*\/(.*)/\1/')
+            find=$(echo "$str" | sed -nE "/\-#$file#\-/p")
+            if [ -z "$find" ]
+            then 
+                str="$str--#$file#-"
+            fi
+        fi
+    done
+    # Current Directory
+    for file in *
+    do 
+        if [ -f "$file" ]
+        then
+            find=$(echo "$str" | sed -nE "/\-#$file#\-/p")
+            if [ -z "$find" ]
+            then 
+                str="$str-#$file#-"
+            fi
+        fi
+    done
+    echo "$str" | sed -E 's/#\-+#/,/g' | sed -E 's/(\-#|#\-)//g' | sed -E $'s/,/\n/g' | sort | tr '\n' ',' | sed 's/.$//'
+}
+
+# Given comma separated list of files, print status for each file in order
+# Usage: print_status <comma list>
+print_status () {
+    for file in $(echo "$1" | sed "s/,/ /g")
+    do
+        echo "$file"
+    done
+}
+
+######################################################################
+# Main
+######################################################################
+
+list=$(get_unique_files)
+
+print_status "$list"
