progress

diff --git a/tigger/tigger-commit b/tigger/tigger-commit
--- a/tigger/tigger-commit
+++ b/tigger/tigger-commit
@@ -13,42 +13,38 @@ check_tigger () {
     fi
 }
 
-# Return the next new commit number
-# Usage: get_new_commit 
-get_new_commit () {
-    if [ -f .tigger/last_commit ] 
-    then
-        last_commit=$(cat .tigger/last_commit)
-        echo "$((last_commit + 1))"
+# Get last commit number if there is one otherwise return -1
+# Usage: get_last_commit
+get_last_commit () {
+    last_commit=$(ls .tigger/commits | tr ' ' '\n' | tail -n 1)
+    if [ -z "$last_commit" ]
+    then 
+        echo "-1"
     else
-        echo "0"
+        echo "$last_commit"
     fi
 }
 
 # Check if there are any current changes between given last commit and index
 # Usage: check_last_commit_diff 
 check_last_commit_diff () {
-    if [ -f .tigger/last_commit ] 
-    then
-        last_commit=$(cat .tigger/last_commit)
-        diff=$(diff -r .tigger/"$last_commit" .tigger/index)
-        if [ -z "$diff" ] 
-        then 
-            echo "nothing to commit"
-            exit 1
-        fi
+    last_commit=$(get_last_commit)
+    if [ "$last_commit" -ge 0 ] && [ -z "$(diff -r .tigger/commits/"$last_commit" .tigger/index)" ] || [ "$last_commit" -eq -1 ] && [ -z "$(ls .tigger/index)" ]
+    then 
+        echo "nothing to commit"
+        exit 1
     fi
 }
 
 # Given a commit number, commit the changes in tigger
 # Usage: commit <commit> <message>
 commit () {
-    mkdir ".tigger/$1"
+    mkdir .tigger/commits/"$1"
     for file in .tigger/index/*
     do 
         if [ -f "$file" ] 
         then 
-            cp "$file" .tigger/"$1"
+            cp "$file" .tigger/commits/"$1"
         fi
     done
     echo "$2" > .tigger/message/"$1"
@@ -58,14 +54,18 @@ commit () {
 
 # Add files to index (tigger-add functionality)
 add_to_index () {
-    for file in *
+    for index_file in .tigger/index/*
     do
-        if [ ! -f "$file" ]
+        if [ -f "$index_file" ] 
         then
-            echo "tigger-commit: error: can not open '$file'"
-            exit 1
+            file=$(echo "$index_file | sed -E 's/.tigger\/index\/(.*)/\1/'")
+            if [ ! -f "$file" ]
+            then
+                echo "tigger-commit: error: can not open '$file'"
+                exit 1
+            fi
+            cp "$file" .tigger/index
         fi
-        cp $file .tigger/index
     done
 }
 
@@ -75,7 +75,7 @@ add_to_index () {
 
 check_tigger
 
-new_commit=$(get_new_commit)
+new_commit=$(($(get_last_commit) + 1))
 
 # Case 1: tigger-commit -a -m <message>
 if [ "$1" = "-a" ] && [ "$2" = "-m" ] && [ ! -z "$3" ]
