update tigger init and test

diff --git a/tigger/tigger-init b/tigger/tigger-init
--- a/tigger/tigger-init
+++ b/tigger/tigger-init
@@ -1,11 +1,37 @@
 #!/bin/dash
 
-if [ -d ".tigger" ]
-then
-    echo "tigger-init: error: .tigger already exists"
-else
+######################################################################
+# Helper Functions
+######################################################################
+
+# Error check: .tigger exists 
+check_tigger () {
+    if [ -d ".tigger" ]
+    then
+        echo "tigger-init: error: .tigger already exists"
+        exit 1
+    fi
+}
+
+make_tigger () {
     mkdir .tigger
-    mkdir .tigger/index .tigger/message
+    mkdir .tigger/index .tigger/message .tigger/commits
     echo "Initialized empty tigger repository in .tigger"
+}
+
+######################################################################
+# Main
+######################################################################
+
+check_tigger
+
+# Case 1: tigger-init
+if [ -z "$1" ]
+then    
+    make_tigger
+# Default - raise usage error
+else 
+    echo "usage: tigger-init"
+    exit 1
 fi
 
